version: '3'

services:
  backend:
    build: ./backend
    ports:
      - "3333:3333"
    volumes:
      - backend-data:/app/database

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: always

  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend 

volumes:
  backend-data:
